#!/usr/bin/env python3
"""
Send EDM Preview B & C final versions with embedded CID images.
Uses multipart/related + multipart/alternative for maximum email client compatibility.
"""
import smtplib
import ssl
import os
import sys
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from email.mime.image import MIMEImage
from email.mime.base import MIMEBase
from email import encoders

# SMTP Config
SMTP_SERVER = "mail.area2.com"
SMTP_PORT = 587
USERNAME = "oc-master@area2.com"
PASSWORD = "sujtyz-wumvUk-1xuccu"
FROM_EMAIL = "ai-agent@area2.com"
FROM_NAME = "AutoLink Account Automation"
TO_EMAIL = os.environ.get("TO_EMAIL", "eric@area2.com")

BASE = "/home/openclaw/.openclaw/workspace/data/projects/area2"
IMG_DIR = "/tmp/openclaw"

edm_configs = [
    {
        'html_file': f'{BASE}/edm-preview-b-final-20260316.html',
        'image_file': f'{IMG_DIR}/edm-hero-b-url-20260316.png',
        'image_cid': 'hero-b-final',
        'subject': 'AutoLink 一站式會計及審計服務 — 專業顧問為您度身安排（附WhatsApp CTA）',
    },
    {
        'html_file': f'{BASE}/edm-preview-c-final-20260316.html',
        'image_file': f'{IMG_DIR}/edm-hero-c-url-20260316.png',
        'image_cid': 'hero-c-final',
        'subject': 'AutoLink 一站式會計及審計服務 — 限時優惠即將截止（附WhatsApp CTA）',
    },
]

def build_email(config):
    """
    Build a multipart/related email with CID-embedded hero image.
    Structure:
      multipart/related
        ├── multipart/alternative
        │     ├── text/plain (fallback)
        │     └── text/html  (the EDM)
        └── image/png (CID embedded)
    """
    # Outer: multipart/related (ties HTML + images together)
    msg = MIMEMultipart('related')
    msg['Subject'] = config['subject']
    msg['From'] = f'{FROM_NAME} <{FROM_EMAIL}>'
    msg['To'] = TO_EMAIL
    msg['Reply-To'] = 'sales@autolink.com.hk'

    # Inner: multipart/alternative (text + html)
    msg_alt = MIMEMultipart('alternative')

    # Plain text fallback
    plain = f"""\
AutoLink 一站式會計及審計服務

2026年3月31日前確認，即可尊享：
• 免費首次稅務狀況評估諮詢（價值 $1,000）
• 服務費 9 折優惠

WhatsApp 查詢：+852 9501 6798
電郵：sales@autolink.com.hk

---
© 2026 AutoLink Account Automation
EDM generated by Hostlink AI Agent: https://www.hostlink.com.hk/zh-hant/ai-solution/
"""
    msg_alt.attach(MIMEText(plain, 'plain', 'utf-8'))

    # HTML content
    with open(config['html_file'], 'r', encoding='utf-8') as f:
        html_content = f.read()
    msg_alt.attach(MIMEText(html_content, 'html', 'utf-8'))

    msg.attach(msg_alt)

    # Embed hero image as CID attachment
    with open(config['image_file'], 'rb') as f:
        img_data = f.read()

    img_mime = MIMEImage(img_data, _subtype='png')
    img_mime.add_header('Content-ID', f'<{config["image_cid"]}>')
    img_mime.add_header('Content-Disposition', 'inline',
                        filename=f'{config["image_cid"]}.png')
    # X-Attachment-Id helps Gmail display CID images
    img_mime.add_header('X-Attachment-Id', config['image_cid'])
    msg.attach(img_mime)

    return msg


def send_email(msg, label):
    """Send via SMTP with STARTTLS."""
    try:
        server = smtplib.SMTP(SMTP_SERVER, SMTP_PORT, timeout=30)
        server.ehlo()
        server.starttls(context=ssl._create_unverified_context())
        server.ehlo()
        server.login(USERNAME, PASSWORD)
        server.sendmail(FROM_EMAIL, TO_EMAIL, msg.as_string())
        server.quit()
        print(f'✅ Sent: {label}')
        return True
    except Exception as e:
        print(f'❌ Failed: {label} — {e}')
        return False


if __name__ == '__main__':
    print('=' * 60)
    print(f'Sending EDM Preview B & C Final to {TO_EMAIL}')
    print('=' * 60)

    ok = 0
    for cfg in edm_configs:
        # Verify files exist
        for key in ('html_file', 'image_file'):
            if not os.path.exists(cfg[key]):
                print(f'❌ Missing: {cfg[key]}')
                sys.exit(1)

        msg = build_email(cfg)
        label = cfg['subject']
        if send_email(msg, label):
            ok += 1

    print('=' * 60)
    print(f'Result: {ok}/{len(edm_configs)} emails sent')
    print('=' * 60)
    sys.exit(0 if ok == len(edm_configs) else 1)
